CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED WITH mysql_native_password BY 'repl123';

GRANT REPLICATION SLAVE, REPLICATION CLIENT
ON *.*
TO 'repl'@'%';

FLUSH PRIVILEGES;

-- 

CHANGE REPLICATION SOURCE TO
SOURCE_HOST='mysql-master',
SOURCE_PORT=3306,
SOURCE_USER='repl',
SOURCE_PASSWORD='repl123',
SOURCE_AUTO_POSITION=1;

START REPLICA;